---
title: "RapidFieldAssessments"
author: "VB"
date: "2024-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data, echo=FALSE}
library(readxl)
Soils <- read_excel("~/Downloads/Rapid Field Assessment Data.xlsx", 
    sheet = "Soils")
library(readxl)
Silvopasture <- read_excel("~/Downloads/Rapid Field Assessment Data (1).xlsx", 
    sheet = "Pasture")
library(readxl)
Vegetation <- read_excel("~/Downloads/Rapid Field Assessment Data (1).xlsx", 
    sheet = "Other Veg")
```


```{r load liibraries, echo=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(wesanderson)
library(ggsci)
library(viridisLite)
```

```{r soil change and pivot}
cleaned_data <- Soils %>%
  select(-Horizon_1, -Horizon_1_depth, -Horizon_2, -Horizon_2_depth, 
         -Horizon_3, - Horizon_3_depth)

reshaped_soils <- cleaned_data %>%
  pivot_wider(names_from = horizon_number, 
              values_from = c(horizon_type, depth_cm),
              names_sep = "_horizon_")

soils_new <- reshaped_soils %>% 
  select(-depth_cm_horizon_ND, -depth_cm_horizon_NA, -horizon_type_horizon_NA, 
         -horizon_type_horizon_ND, -Sample_Notes)

soils_new_clean <- soils_new %>% 
  mutate(bare_soil_percent = as.numeric(replace(bare_soil_percent, bare_soil_percent == "ND", NA)))
```

```{r soil summary stats}
o_horizon_data <- soils_new %>%
  filter(horizon_type_horizon_1 == "O")
o_horizon_data <- o_horizon_data %>%
  separate(depth_cm_horizon_1, into = c("depth_start", "depth_end"), 
           sep = "-", convert = TRUE)

o_horizon_data %>%
  summarize(
    mean_depth_end = mean(depth_end),
    median_depth_end = median(depth_end),
    sd_depth_end = sd(depth_end))
```

```{r mulch, bare, CWD}
soils_new %>% 
  count(mulch_leaves_type)

soils_new %>% 
  count(CWD)

soils_new_clean %>% 
  summarize(avg_bare = mean(bare_soil_percent, na.rm = TRUE))
```

```{r pasture summary}
silvo_summary <- Silvopasture %>% 
  summarize(mean_legumes = mean(legumes_percent), 
            median_legumes = median(legumes_percent), 
            mean_grass = mean(grass_percent), 
            median_grass = median(grass_percent), 
            mean_other = mean(other_plants_percent), 
            median_other = median(other_plants_percent)) 

Silvopasture %>%   
  filter(dot_density != "NA") %>%
            summarize(mean_dots = mean(dot_density, na.rm = TRUE), 
            median_dots = median(dot_density, na.rm = TRUE)
          )

## error reads that NAs introduced by coercion- must go back to original dataset
## and remove NDs to make this easier
```

```{r pasture regression}
bare_soil_lm <- lm(bare_soil_percent ~ canopy_percent, data = Silvopasture)
summary(bare_soil_lm)


forage_height_lm <- lm(forage_yield_in ~ canopy_percent, data = Silvopasture)
summary(forage_height_lm)

#silvo_dot_reduced <- Silvopasture %>%
#  filter(!is.na (dot_density))
#dot_density_lm <- lm(dot_density ~ canopy_percent, data = silvo_dot_reduced)
#summary(dot_density_lm)
```

```{r veg basic summary stats}
##number of distinct species
Vegetation %>%
  distinct(common_name) %>%
  nrow()

##avg percent cover by site
Vegetation %>%
  group_by(farm_name) %>%
  summarize(mean_percent_cover = mean(percent_cover, na.rm = TRUE))
## mean structure value 
Vegetation %>%
  group_by(farm_name) %>%
  summarize(mean_structure = mean(structure, na.rm = TRUE))
#Vegetation %>% 
 # group_by(farm_name) %>%
  #summarize(average_percent_cover = mean(percent_cover))
```

```{r other veg functional groups}
# Frequency of species occurrences
Vegetation %>%
  group_by(common_name) %>%
  summarize(frequency = n_distinct(farm_name)) %>%
  arrange(desc(frequency)) %>% 
  slice(1:10)

#number of different species present in each type of system 
Vegetation %>%
  group_by(system) %>%
  summarize(frequency = n_distinct(common_name)) %>%
  arrange(system, desc(frequency))

species_by_functional_group <- Vegetation %>%
  group_by(system, functional_group) %>%
  summarize(species_count = n_distinct(common_name))

ggplot(species_by_functional_group, aes(x = system, y = species_count, fill = functional_group)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of Species by Functional Group for Each System",
       x = "System Type",
       y = "Number of Species",
       fill = "Functional Group") +
  scale_fill_manual(values = c("herbaceous" = "seagreen", 
                               "shrub/woody plant" = "burlywood2", 
                               "tree" = "sienna2")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r bar graph families}
family_counts <- Vegetation %>% 
  filter(site != "Reference") %>%
  group_by(farm_name) %>%
  summarise(num_families = n_distinct(family))

ggplot(family_counts, aes(x = farm_name, 
                                            y = num_families,
                      fill = farm_name, width = 0.7)) +
  geom_bar(stat = "identity") +
  scale_fill_discrete() + 
  labs(title = "Number of Taxonomic Families Across Sites",
       x = "Site",
       y = "Number of Taxonomic Families") +
  theme_minimal() +
  theme(legend.position = "none",  # Remove the legend
        axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
        plot.title = element_text(hjust = 0.5)) +  # Center the plot title
  scale_x_discrete(labels = function(x) str_wrap(x, width = 25)) 
```

